openapi: 3.0.0
info:
  title: Simple File Server API
  version: 1.0.0
  description: API for managing files and checking server status.
servers:
  - url: http://localhost:5000 # Modifier si nécessaire
paths:
  /files/upload:
    post:
      summary: Upload a new file.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: File upload status and information.
          content:
            application/json:
              schema:
                type: object
                properties:
                  saveStatus:
                    type: string
                    enum:
                      - SAVED
                      - FAILED
                  fileId:
                    type: string
                  fileName:
                    type: string
        '400':
          description: Bad request.
  /files/download/{fileID}:
    get:
      summary: Download a file by ID.
      parameters:
        - name: fileID
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: File download.
          content:
            application/octet-stream: {}
        '500':
          description: Internal server error.
          content:
            text/plain:
              schema:
                type: string
  /files/infos/{fileID}:
    get:
      summary: Get file information by ID.
      parameters:
        - name: fileID
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: File information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileInfo'
        '404':
          description: File not found.
  /ping:
    get:
      summary: Check server status.
      responses:
        '200':
          description: Server is running.
          content:
            text/plain:
              schema:
                type: string
                example: "pong"

components:
  schemas:
    FileInfo:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        mimetype:
          type: string
        size:
          type: integer
        path:
          type: string